stages:
  - Backend
  - Frontend

# Backend Jobs
Test API:
  stage: Backend
  image: python:3.6

  services:
  - postgres:9.6-alpine

  variables:
    POSTGRES_DB: forum_db
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: pass

  script:
    - export FLASK_ENV=test
    - export SPY_LOG_LOGGER="pretty-no-meta"
    - pip install -r Backend/requirements.txt
    - pip install -r Backend/requirements-test.txt
    - pip install -e Backend
    - ./Backend/run-tests.sh


	Code quality:
	  stage: Backend
	  image: docker:stable
	  variables:
	    DOCKER_DRIVER: overlay2
	  allow_failure: true
	  services:
	    - docker:stable-dind
	  script:
	    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
	    - docker run
	        --env SOURCE_CODE="$PWD/Backend/forum_api"
	        --volume "$PWD":/code
	        --volume /var/run/docker.sock:/var/run/docker.sock
	        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
	  artifacts:
	    reports:
	      codequality: gl-code-quality-report.json

# Frontend Jobs
Build App:
  stage: Frontend
  image: java:8-jdk
  before_script:
    - echo `pwd`
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - rm -f  .gradle/caches/modules-2/modules-2.lock
    - rm -fr .gradle/caches/*/plugin-resolution/
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script:
    - ./Frontend/kite_master/gradlew build
