stages:
  - backend
  - frontend


test api:
  stage: backend
  image: python:3.6

  services:
  - postgres:9.6-alpine

  variables:
    POSTGRES_DB: forum_db
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: pass

  script:
    - export FLASK_ENV=test
    - pip install -r Backend/requirements.txt
    - pip install -r Backend/requirements-test.txt
    - pip install -e Backend
    - ./Backend/run-tests.sh

build app:
  stage: frontend
  image: java:8-jdk
  before_script:
    - echo `pwd`
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - rm -f  .gradle/caches/modules-2/modules-2.lock
    - rm -fr .gradle/caches/*/plugin-resolution/
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script:
    - ./Frontend/kite_master/gradlew build