version: "3"
services:
  lb:
    image: traefik
    command: --api --docker
    ports:
      - "5000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Docker/traefik.toml:/traefik.toml
  db:
    restart: always
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "forum_db"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    restart: always
    image: "koozie/kite-beta"
    depends_on:
      - db
    environment:
      FLASK_APP: "forum_api"
      API_DB_HOST: "db"
      API_DB_PORT: "5432"
      API_DB_USERNAME: "admin"
      API_DB_PASSWORD: "pass"
      API_DB_NAME: "forum_db"
      FORUM_ADMIN: "fadmin"
      FORUM_ADMIN_PASS: "pass"
    ports:
      - 9000:9000
    labels:
      - "traefik.basic.frontend.rule=Host:0.0.0.0, localhost"
  chat:
    restart: always
    image: "koozie/kite-chat"
    ports:
      - 5500:5500
    labels:
      - "traefik.basic.frontend.rule=Host:chat.0.0.0.0, chat.localhost"
volumes:
  pgdata:
